version: 2
updates:
  ## Events
  - directory: "src/Events"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

  ## Events.Functions
  - directory: "src/Events.Functions"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
      
## Test
  - directory: "test/Altinn.Platform.Events.Tests"
    package-ecosystem: "nuget"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"

## Dockerfile
  - directory: "/"
    package-ecosystem: "docker"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "07:00"
      timezone: "Europe/Oslo"
