name: Regression Test - AT24

on:
  workflow_dispatch:
  schedule:
  - cron: '0 12 * * 1-5'
  pull_request:
    types: [review_requested, review_request_removed]

jobs:
  at24:
    uses: ./.github/workflows/regression-test-ATX.yml
    with:
      environment: AT24
    secrets: inherit
