name: Use Case - TT02

on:
  workflow_dispatch:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  test:
    environment: TT02
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run app-events use case tests
      run:  |
              cd test/k6
              docker-compose run k6 run /src/tests/app-events.js -e env=${{ vars.ENV }} -e mpClientId=${{ secrets.MP_CLIENT_ID }} -e mpKid=${{ secrets.MP_KID }} -e encodedJwk=${{ secrets.MP_ENCODEDJWK }} -e app=apps-test -e userName=${{ secrets.USER_NAME }} -e userPassword=${{ secrets.USER_PASSWORD }}
    - name: Run events use case tests
      if: always()
      run:  |
              cd test/k6
              docker-compose run k6 run /src/tests/events/post.js -e env=${{ vars.ENV }} -e mpClientId=${{ secrets.MP_CLIENT_ID }} -e mpKid=${{ secrets.MP_KID }} -e encodedJwk=${{ secrets.MP_ENCODEDJWK }}
              docker-compose run k6 run /src/tests/events/get.js -e env=${{ vars.ENV }} -e mpClientId=${{ secrets.MP_CLIENT_ID }} -e mpKid=${{ secrets.MP_KID }} -e encodedJwk=${{ secrets.MP_ENCODEDJWK }}
    - name: Run subscription use case tests
      if: always()
      run:  |
              cd test/k6
              docker-compose run k6 run /src/tests/subscriptions.js -e env=${{ vars.ENV }} -e mpClientId=${{ secrets.MP_CLIENT_ID }} -e mpKid=${{ secrets.MP_KID }} -e encodedJwk=${{ secrets.MP_ENCODEDJWK }} -e app=apps-test -e webhookEndpoint=${{ secrets.WEBHOOK_ENDPOINT }}
    - name: Build failure report
      if: failure()
      run: |
          report=":warning: Events use case test failure in ${{ vars.ENV }} :warning: \n"
          report+="\n Workflow available here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "stepreport="$report >> $GITHUB_ENV
    - name: Report failure to Slack
      if: failure()
      id: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
            {
              "text": "${{ env.stepreport }}"
            }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_PROD }}

